### ISSUE TITLE
GET, POST and DELETE for Favorites

### ISSUE THREAD

**Issue by costibleotu** [costibleotu/creativa#26]
GET /api/favorites:
* first_name
* last_name
* url
* profile_picture

POST /api/favorites
* id 

DELETE /api/favorites
* id

**Comment by costibleotu** [comment]
So, you have now `/en/api/favorites/` with 2 methods:

# GET
Returns favorites in this form:
```
{
    "favorites": [
        {
            "pk": 86,
            "first_name": "Patti",
            "last_name": "Burch",
            "url": "https://dev.creativa.community/en/api/creative/patti-burch/",
            "profile_picture": "https://picsum.photos/id/39/200/200"
        },
        {
            "pk": 89,
            "first_name": "Levy",
            "last_name": "Jacobson",
            "url": "https://dev.creativa.community/en/api/creative/levy-jacobson/",
            "profile_picture": "https://picsum.photos/id/20/200/200"
        },
        {
            "pk": 90,
            "first_name": "Sharpe",
            "last_name": "Sampson",
            "url": "https://dev.creativa.community/en/api/creative/sharpe-sampson/",
            "profile_picture": "https://picsum.photos/id/15/200/200"
        }
    ]
}
```

# POST
Is looking for `favorites` key in `POST`. The request should look like:
```
{'csrfmiddlewaretoken':['vsYeGP5VzTOxt33jumFj8uORTBRT06NF2vNfv0lgnwLCurjTM0Da1srCdqwsCW2v'], 'favorites': ['86', '89', '90']}
```
I say we should user POST for DELETE to.. so if you want to delete a favorite, just send the final list  of favorites.
Should work for now

**Comment by andrei-dracea** [comment]
ok
1. where do I get the CSRF from?
2. should we use a `fav: Boolean` on the sectors and creative API? Otherwise I have to go through the whole sectors object (could be costly)

**Comment by costibleotu** [comment]
1. I will take out the csrf on this one. It’s safe, considering the
endpoint runs only in the context of the logged in user
2. Will do that :)

**Comment by costibleotu** [comment]
1. Done
2. Now you have `is_fac` on each creative from each category in `/api/sectors`
![image](https://user-images.githubusercontent.com/1089585/70946714-59935b00-2060-11ea-87c4-8f6706c905dc.png)]
You also have `favorites` under the `/api/stats`
![image](https://user-images.githubusercontent.com/1089585/70946887-ad05a900-2060-11ea-86ee-0def536a2550.png)

**Comment by costibleotu** [comment]
Close issue if everything is ok

**Comment by andrei-dracea** [comment]
I can't POST json.. not working on API test interface either

**Comment by andrei-dracea** [comment]
Also, don't need favorites in stats, because it is synced with `favorites.length`

**Comment by costibleotu** [comment]
> I can't POST json.. not working on API test interface either

Try now, pls
:*
