### ISSUE TITLE
Add computed height of blocks to api

### ISSUE THREAD

**Issue by andrei-dracea** [costibleotu/creativa#9]
Consideram max = 100% si min = 0%, astfel pt fiecare valoare (x) trebuie calculat procentul
```
p = (x - min)/(max - min) * 100
```
Apoi eu pot jongla cu procentul asta si sa-mi setez max/min cum vreau eu :)

**Comment by costibleotu** [comment]
Cum trebuie sa fie calculata inaltimea? (cat este procentul la fiecare bloc?)
